### ISSUE TITLE
ModuleNotFoundError: No module named 'cnn_data_augmentations'

### ISSUE THREAD

**Issue by mxochicale** [tarakapoor/thyroid_deep_learning#2]
Hiya, 

Thanks for sharing your work, I have forked your repo to replicate your work but seems that `cnn_data_augmentations.py` is missing in your original commits, causing the following error: 
```
(transformersVE) :~/repositories/thyroid_deep_learning$ python cnn_main.py
Home directory argument in my code:/your/home/dir
Traceback (most recent call last):
  File "~/repositories/thyroid_deep_learning/cnn_main.py", line 53, in <module>
    import train_cnn #train_model (for cnn)
  File "~/repositories/thyroid_deep_learning/train_cnn.py", line 1, in <module>
    from cnn_data_augmentations import *
ModuleNotFoundError: No module named 'cnn_data_augmentations'
```

Would you please upload it?

Ps. At some point in coming days, I will be able to submit few changes https://github.com/mxochicale/thyroid_deep_learning to yours. They might improve reproducibility and readability of the repo!

Thanks, Miguel

**Comment by mxochicale** [comment]
Just found it in one of your earliest commits but would you like to confirm that you use the same one for your latest commits?  
https://github.com/tarakapoor/thyroid_deep_learning/blob/4987a460967f5f16133e26d156b2a456ab8d6cce/cnn_data_augmentations.py 

```
from albumentations.pytorch import ToTensorV2
import albumentations as A
import cv2


transformAug = A.Compose([
    A.HorizontalFlip(p=0.9),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    #A.RandomContrast(limit=0.2, p=1.0),
    A.ShiftScaleRotate(shift_limit=0.2, scale_limit=0.2, rotate_limit=20, border_mode=cv2.BORDER_CONSTANT, p=0.4),
    A.Cutout(num_holes=2, max_h_size=int(0.25*224), max_w_size=int(0.25*224), fill_value=0, always_apply=True, p=0.9),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])

transformNorm = A.Compose([
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])
```

Also to mention that I got this one : "ImportError: cannot import name 'ToTensor' from 'albumentations.pytorch' (~/anaconda3/envs/transformersVE/lib/python3.10/site-packages/albumentations/pytorch/__init__.py") to which I comment
```
# from albumentations.pytorch import ToTensor 
```

**Comment by mxochicale** [comment]
Thanks to Tara Kapoor who shared the following one, confirming the above script.

```
from albumentations.pytorch import ToTensorV2
from albumentations.pytorch import ToTensor
import albumentations as A
import cv2

transformAug = A.Compose([
    A.HorizontalFlip(p=0.9),
    A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.5),
    #A.RandomContrast(limit=0.2, p=1.0),
    A.ShiftScaleRotate(shift_limit=0.2, scale_limit=0.2, rotate_limit=20, border_mode=cv2.BORDER_CONSTANT, p=0.4),
    A.Cutout(num_holes=2, max_h_size=int(0.25*224), max_w_size=int(0.25*224), fill_value=0, always_apply=True, p=0.9),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])

transformNorm = A.Compose([
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2(),
])
```
which is now committed here https://github.com/mxochicale/thyroid_deep_learning/blob/0626504423cf44a7e2061a9b3e53f288676160c2/cnn_data_augmentations.py

I close this one but bare in mind that further tests with its call will come.
